g_cells_in_parallel = 10;
g_cells_in_series = 12;
g_cell_diam = 18;
g_cell_hspace = 5;
g_cell_vspace = -3;
g_row_offset = (g_cell_diam + g_cell_hspace)/2;
g_wall_vspace = 5;
g_wall_hspace = 20;
g_wall_thickness = 1;
